### ISSUE TITLE
Center lane type

### ISSUE THREAD

**Issue by dbeckerAC** [ika-rwth-aachen/RoadGeneration#13]
According to OpenDRIVE the center lane with `id=0` shall have `type="none"`.

Right now  `type="driving"` is set. At least in some examples I saw.

Or am I wrong?

**Comment by jannikbusse** [comment]
fixed in 0cad81307c34a42014fff9e4622a8c3352ebef0d

**Comment by jannikbusse** [comment]
Fixed in 0cad81307c34a42014fff9e4622a8c3352ebef0d
